### PR TITLE
Code Cleanup

### PR DESCRIPTION
**Pull request by Ruckamongus**
Includes fixing const correctness, misspellings, reording the header declarations alphabetically, removing duplicate functions, and moving functions to globalfunctions.cpp/h.

### CODE REVIEW

**Review by Ruckamongus — COMMENTED** [review]
Includes fixing const correctness, misspellings, reording the header declarations alphabetically, removing a duplicate function, and moving dist() and distEucledian() to globalfunctions.cpp/h.

**Comment by Ruckamongus** [comment]
I know there is A LOT here, but I think it will help things stay organized.

After you consider accepting/declining this I was wondering about your thoughts on unifying coordinates. Many functions take a "cords" argument, there is an "std::pair<int, int>", and many functions take "int x, int y." I propose passing around a "cord" in all of these places. If this is done the number of static_casts can probably be cut down and line length can be shortened. Thoughts? If you like the idea I want to take a shot at doing it.

**Comment by switchboy** [comment]
First off that must have been a lot of work. I am sold on the optimazation gains of const correctness. However for performance and memory usage I purposefully pass a lot of values by reference where I can. (so the CPU is not wasting valuable resources in creating new space in memory for something that will get destroyed just an instance later). Some functions are called a couple of hundred times in a row. By trial and error I found out that especially in tasks like pathfinding and updating the state of a hundred busy actors this massively improved performance. In rearranging I see you have removed most of them. . As it stands some functions are already tanking the frame rate. So pass-by-const-reference would be my preferred way of treating values which are already somewhere in memory and do not need changing by the function it is passed to. 

As a sidenote:
The add and substract resources functions are written out so it is just obvious what you are doing (verbally) when writing code. Also costs and income from something can just be positive value living somewhere. It makes things easier. 
And I am not a fan of namespaces

**Comment by Ruckamongus** [comment]
So passing by reference is something I agree with, but for trivial data types (int, char, etc.) it doens't make sense unless you actually want the variable to be changed in the function. It is actually more work to use references in this case [look at the produced assembly as an example here](https://godbolt.org/z/q7xn69jPo) and [the explanation by the C++ Core Guidelines](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#fcall-parameter-passing). For larger structs or classes I agree passing by references makes a LOT more sense.

Add and subtract functions: makes sense.

Anonymous namespaces are the same thing as making a function static; they are only defined in the translation unit they are implemented in meaning they don't clutter (and potentially clash) linkage space after compilation.

**Pull request merged**
